version: '3.7'
services:
  postgres:
   image: postgres:11-alpine
   restart: always
   ports:
     - 5432:5432
   volumes:
     - "test-data-volume:/var/lib/postgresql/data"
     - "./build/init:/docker-entrypoint-initdb.d"
   environment:
     POSTGRES_DB: development_database
     POSTGRES_USER: testuser
     POSTGRES_PASSWORD: testpass
     PGDATA: /var/lib/postgresql/data/pgdata
volumes:
  test-data-volume: