"""empty message

Revision ID: 31682976550d
Revises: 
Create Date: 2021-10-19 23:02:50.487917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31682976550d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation')
    # ### end Alembic commands ###
